### PR TITLE
Fix circle

### PR DESCRIPTION
**Pull request by T4rk1n**
- Use cp instead of copyfiles for copying the package.json, fixing the circleci build on python 3.6.
- Remove broken `build-dist` npm script from #60.

### CODE REVIEW

**Comment by rmarren1** [comment]
I think there's more stuff we can remove from `package.json`
```
 "scripts": {
    "clean-lib": "rm -rf lib/* && mkdir -p lib",  <-- The 'lib' folder is not used anymore, I we can probably remove
    "clean-src": "rm -rf src/* && mkdir -p src/components", 
    "clean": "npm run clean-lib && npm run clean-src", <-- We can remove 
    "copy-lib": "cp lib/* dash_html_components",  <-- Can remove since 'lib' is not used
    "generate-python-classes": "python -c 'import dash; dash.development.component_loader.generate_classes(\"dash_html_components\", \"dash_html_components/metadata.json\")'",
    "generate-components": "cd scripts && sh generate-all.sh && cd -",
    "install-local": "npm run copy-lib && python setup.py install",  <-- Can remove copy-lib
    "prepublish": "npm run clean && npm run generate-components && npm test && ./node_modules/.bin/builder run build-dist && npm run copy-lib",  <-- I think we can remove this whole thing
    "publish-pypi": "npm run prepublish && python setup.py sdist upload", <-- I think we have to use twine now
    "publish-all": "npm publish && python setup.py sdist upload", <-- twine?
    "start": "./node_modules/.bin/builder run build-dev", <-- this is different from boilerplate `"start": "webpack-serve ./webpack.serve.config.js --open"`
    "build-dist": "builder run extract-metadata && builder run build-dist", <-- I think we can remove this and just use build:py && build:js
    "test": "./node_modules/.bin/eslint --fix src",
    "uninstall-local": "pip uninstall dash-html-components -y",
    "build:js": "webpack --mode production",
    "build:py": "node ./extract-meta src/components > dash_html_components/metadata.json && copyfiles package.json dash_html_components" <-- should add generate-python-classes step here
  },
```

**Comment by T4rk1n** [comment]
@rmarren1 I cleaned up `package.json`. I think the install bug is gone, please review.

**Comment by rmarren1** [comment]
Can you also add `generate-python-classes` to the `build:py` like it is in the [boilerplate](https://github.com/plotly/dash-component-boilerplate/blob/1d2ee1d9fc1b6fa834fda3dc38064297f8154085/package.json#L10)

**Comment by T4rk1n** [comment]
@rmarren1 Added.

**Comment by rmarren1** [comment]
This looks good to me! :dancer:

**Pull request merged**
