### PR TITLE
Move PropTypes from React package to prop-types

### PR DESCRIPTION
**Pull request by mjclawar**
### Description
This moves the `PropTypes` import from `react` to `prop-types`.

Example:
```js
import React, { PropTypes } from 'react';
```

is now
```js
import React from 'react';
import PropTypes from 'prop-types';
```

This will allow `dash-html-components` to support React 16+ by patching in different versions to the `dash-renderer` by the Dash developer (for now).

For example, in the application definition file:
```python
import dash_renderer
dash_renderer._js_dist_dependencies = [
                {
                    'external_url': [
                        'https://unpkg.com/react@16/umd/react.production.min.js',
                        'https://unpkg.com/react-dom@16/umd/react-dom.production.min.js'
                    ],
                    'relative_package_path': [
                        'react.production.min.js',  # where the user has added this file to the installed dash-renderer for now
                        'react-dom.production.min.js'  # where the user has added this file to installed dash-renderer for now
                    ],
                    'namespace': 'dash_renderer'
                }
            ]
```

### Changes
- Added `package-lock.json`
- Ran the https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types PropTypes codemod from React organization
- Updated the version to 0.9.0

### CODE REVIEW

**Comment by chriddyp** [comment]
This looks good to me! I'm adding some standard dash integration tests in a separate PR so once that's merged into master let's just rebase this PR off of master so that tests run

**Comment by mjclawar** [comment]
OK. Just @ me when that's all set and I'll rebase.

**Comment by chriddyp** [comment]
alright @mjclawar - tests were added in #38

**Comment by mjclawar** [comment]
@chriddyp should be good now.

**Comment by chriddyp** [comment]
thanks @mjclawar ! I'll make a new release shortly

**Comment by chriddyp** [comment]
@mjclawar `v0.9.0` has been released 🍻

**Comment by mjclawar** [comment]
Nice! Did the same update for `dash-core-components` in https://github.com/plotly/dash-core-components/pull/160

51acfgh8ibl _sx258_bo1 204 203 200_

**Pull request merged**
